### ISSUE TITLE
Other nodes?

### ISSUE THREAD

**Issue by kosirm** [SamuliRiihikoski/NodeCustomBuilder#2]
It would be great if it would work also for animation nodes...
I know this is a free plugin, but anyway...

Keep good work. BR

**Comment by SamuliRiihikoski** [comment]
It’s possible to do, but I haven’t found a good way to do it yet. The main issue is that animations in nodes are very scene linked. So if user saves animated nodes in one scene it really dosen’t work with other scene and user ends up to edit all animated nodes and it takes too much time. If someone has a good idea how handle this I’m all ears

**Comment by kosirm** [comment]
Thanks!
